### ISSUE TITLE
Apps Check out all ok need 1 more 

### ISSUE THREAD

**Issue by StarfighterJ** [pparedes1/alexa-lgtv-remote#6]
Apps Check out all ok need 1 more **user guide.**
also possible changes:
I have **photo** instead of pictures, and **lgstore** instead of lgcontent. 
If not let me know I'll change it to yours.
Also if you got time can you give me walk through on getting this on Heroku, the tutorial has got me stuck with a bug in it.
Thank you 
Jay

**Comment by pparedes1** [comment]
added user guide and went with your naming convention. Sorry for blowing up your repo, I figured it was easier to clean up with the same commits than making another commit for something so small. 

For Heroku, have you pushed your repository to Heroku? what errors are you getting when you push? I have a separate heroku remote repository that I use for this app which is essentially pointing to the same commit as my master in my local repository. If this doesn't make sense, let me know since I have to assume you can push your repo to heroku based on what's on your local machine. 

One thing you might consider is having an environment variable YARN_PRODUCTION=false as this tells Heroku to install all the dev_dependencies from package.json and it could be one source of compilation issues. Let me know what your logs on your console are saying...

**Comment by StarfighterJ** [comment]
LOL  I must had tried everything for User Guide except tvuserguide. is there a list of those some where in case I add more APPS? The Inputs work great by the way even my costume stuff.

Going to start a Turn off and Turn on Issue

**Comment by pparedes1** [comment]
I used [this](https://github.com/klattimer/LGWebOSRemote) python program to connect to my tv and ran the listApps command. It returns a JSON of all the apps installed on your tv. Obviously that's another route you could take with your project if you are more comfortable in python.
